version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - '27015:27015'
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    environment:
      - DB_URI='mongodb://172.17.255.255:27015/db-name'
      - JWT_SECRET_KEY='9zVW]9cBNMbO'
      - SENDER_MAIL='sample@gmail.com'
      - SENDER_MAIL_PW='123'
    ports:
      - '8080:8080'
    external_links:
      - mongo